[2025-02-12T00:03:59.412+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T00:03:59.476+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Upload_data_to_s3 scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-12T00:03:59.496+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_for_dbt_raw.Upload_data_to_s3 scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-12T00:03:59.497+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T00:03:59.552+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-09 00:00:00+00:00
[2025-02-12T00:03:59.568+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T00:03:59.570+0000] {standard_task_runner.py:72} INFO - Started process 359 to run task
[2025-02-12T00:03:59.576+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_for_dbt_raw', 'Upload_data_to_s3', 'scheduled__2025-02-09T00:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dbt_raw_dag.py', '--cfg-path', '/tmp/tmp9juge1na']
[2025-02-12T00:03:59.580+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask Upload_data_to_s3
[2025-02-12T00:03:59.747+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_for_dbt_raw.Upload_data_to_s3 scheduled__2025-02-09T00:00:00+00:00 [running]> on host ecdf8258250e
[2025-02-12T00:03:59.946+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_for_dbt_raw' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-09T00:00:00+00:00'
[2025-02-12T00:03:59.948+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T00:05:46.274+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-12T00:07:48.857+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-12T00:14:02.914+0000] {logging_mixin.py:190} INFO - uploaded file num.txt
[2025-02-12T00:14:07.379+0000] {logging_mixin.py:190} INFO - uploaded file tag.txt
[2025-02-12T00:14:07.582+0000] {logging_mixin.py:190} INFO - uploaded file readme.htm
[2025-02-12T00:14:07.720+0000] {python.py:240} INFO - Done. Returned value was: success
[2025-02-12T00:14:08.259+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T00:14:08.272+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_for_dbt_raw, task_id=Upload_data_to_s3, run_id=scheduled__2025-02-09T00:00:00+00:00, execution_date=20250209T000000, start_date=20250212T000359, end_date=20250212T001408
[2025-02-12T00:14:08.665+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T00:14:08.874+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T00:14:08.880+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
