[2025-02-08T22:40:38.979+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_python.fireCrawl scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T22:40:38.998+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_python.fireCrawl scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T22:40:38.999+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T22:40:39.000+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-02-08T22:40:39.000+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T22:40:39.029+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fireCrawl> on 2025-02-07 00:00:00+00:00
[2025-02-08T22:40:39.039+0000] {standard_task_runner.py:55} INFO - Started process 203 to run task
[2025-02-08T22:40:39.043+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python', 'fireCrawl', 'scheduled__2025-02-07T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp9b41ap3l']
[2025-02-08T22:40:39.044+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask fireCrawl
[2025-02-08T22:40:39.196+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python.fireCrawl scheduled__2025-02-07T00:00:00+00:00 [running]> on host b8c15fc2b044
[2025-02-08T22:40:39.345+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_python
AIRFLOW_CTX_TASK_ID=fireCrawl
AIRFLOW_CTX_EXECUTION_DATE=2025-02-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-02-07T00:00:00+00:00
[2025-02-08T22:40:39.350+0000] {firecrawl.py:32} WARNING - No API key provided
[2025-02-08T22:40:39.352+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 19, in get_links
    app = FirecrawlApp(api_key=os.getenv('FIRE_CRAWL'))
  File "/home/airflow/.local/lib/python3.7/site-packages/firecrawl/firecrawl.py", line 33, in __init__
    raise ValueError('No API key provided')
ValueError: No API key provided
[2025-02-08T22:40:39.389+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_python, task_id=fireCrawl, execution_date=20250207T000000, start_date=20250208T224038, end_date=20250208T224039
[2025-02-08T22:40:39.415+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task fireCrawl (No API key provided; 203)
[2025-02-08T22:40:39.446+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-08T22:40:39.478+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
