[2025-02-11T23:46:45.778+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T23:46:45.800+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-11T18:46:34-05:00 [queued]>
[2025-02-11T23:46:45.816+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-11T18:46:34-05:00 [queued]>
[2025-02-11T23:46:45.816+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T23:46:45.835+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-11 23:46:34+00:00
[2025-02-11T23:46:45.842+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T23:46:45.846+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2025-02-11T23:46:45.845+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_to_scrape_and_upload', 'Upload_data_to_s3', 'manual__2025-02-11T18:46:34-05:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/scrape_upload_dag.py', '--cfg-path', '/tmp/tmp8unmew0c']
[2025-02-11T23:46:45.846+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask Upload_data_to_s3
[2025-02-11T23:46:45.903+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-11T18:46:34-05:00 [running]> on host ecdf8258250e
[2025-02-11T23:46:46.031+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_to_scrape_and_upload' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T23:46:34+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:46:34-05:00'
[2025-02-11T23:46:46.033+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T23:47:05.401+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-11T23:47:19.147+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-11T23:48:21.594+0000] {logging_mixin.py:190} INFO - uploaded file num.txt
[2025-02-11T23:48:29.359+0000] {logging_mixin.py:190} INFO - uploaded file tag.txt
[2025-02-11T23:48:29.554+0000] {logging_mixin.py:190} INFO - uploaded file readme.htm
[2025-02-11T23:48:29.580+0000] {python.py:240} INFO - Done. Returned value was: success
[2025-02-11T23:48:29.623+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T23:48:29.625+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_to_scrape_and_upload, task_id=Upload_data_to_s3, run_id=manual__2025-02-11T18:46:34-05:00, execution_date=20250211T234634, start_date=20250211T234645, end_date=20250211T234829
[2025-02-11T23:48:29.698+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T23:48:29.724+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T23:48:29.727+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
