[2025-02-09T09:16:15.324+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T09:16:15.366+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-09T09:16:11.081422+00:00 [queued]>
[2025-02-09T09:16:15.384+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-09T09:16:11.081422+00:00 [queued]>
[2025-02-09T09:16:15.385+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-09T09:16:15.409+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Upload_data_to_s3> on 2025-02-09 09:16:11.081422+00:00
[2025-02-09T09:16:15.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_to_scrape_and_upload', 'Upload_data_to_s3', 'manual__2025-02-09T09:16:11.081422+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/scrape_upload_dag.py', '--cfg-path', '/tmp/tmpyggkbgh1']
[2025-02-09T09:16:15.422+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T09:16:15.427+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask Upload_data_to_s3
[2025-02-09T09:16:15.428+0000] {standard_task_runner.py:72} INFO - Started process 255 to run task
[2025-02-09T09:16:15.536+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_to_scrape_and_upload.Upload_data_to_s3 manual__2025-02-09T09:16:11.081422+00:00 [running]> on host efe809b20a4e
[2025-02-09T09:16:15.808+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_to_scrape_and_upload' AIRFLOW_CTX_TASK_ID='Upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T09:16:11.081422+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T09:16:11.081422+00:00'
[2025-02-09T09:16:15.812+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T09:16:27.001+0000] {logging_mixin.py:190} INFO - uploaded file sub.txt
[2025-02-09T09:17:04.043+0000] {logging_mixin.py:190} INFO - uploaded file pre.txt
[2025-02-09T09:17:14.555+0000] {job.py:229} INFO - Heartbeat recovered after 13.54 seconds
[2025-02-09T09:17:14.593+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-02-09T09:17:14.628+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T09:17:14.633+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
