[2025-02-08T22:53:25.863+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_python.fireCrawl manual__2025-02-08T22:53:20.062276+00:00 [queued]>
[2025-02-08T22:53:25.882+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_with_python.fireCrawl manual__2025-02-08T22:53:20.062276+00:00 [queued]>
[2025-02-08T22:53:25.883+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T22:53:25.884+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-02-08T22:53:25.884+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-02-08T22:53:25.906+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fireCrawl> on 2025-02-08 22:53:20.062276+00:00
[2025-02-08T22:53:25.932+0000] {standard_task_runner.py:55} INFO - Started process 271 to run task
[2025-02-08T22:53:25.935+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python', 'fireCrawl', 'manual__2025-02-08T22:53:20.062276+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp19ay77bg']
[2025-02-08T22:53:25.936+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask fireCrawl
[2025-02-08T22:53:26.044+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python.fireCrawl manual__2025-02-08T22:53:20.062276+00:00 [running]> on host 1694b062ea20
[2025-02-08T22:53:26.162+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_python
AIRFLOW_CTX_TASK_ID=fireCrawl
AIRFLOW_CTX_EXECUTION_DATE=2025-02-08T22:53:20.062276+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-08T22:53:20.062276+00:00
[2025-02-08T22:53:26.164+0000] {firecrawl.py:32} WARNING - No API key provided
[2025-02-08T22:53:26.166+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 19, in get_links
    app = FirecrawlApp(api_key=os.getenv('FIRE_CRAWL'))
  File "/home/airflow/.local/lib/python3.7/site-packages/firecrawl/firecrawl.py", line 33, in __init__
    raise ValueError('No API key provided')
ValueError: No API key provided
[2025-02-08T22:53:26.211+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_with_python, task_id=fireCrawl, execution_date=20250208T225320, start_date=20250208T225325, end_date=20250208T225326
[2025-02-08T22:53:26.237+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task fireCrawl (No API key provided; 271)
[2025-02-08T22:53:26.257+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-02-08T22:53:26.282+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
